/* Generated by Yosys 0.56+171 (git sha1 6fdcdd41d, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

(* top =  1  *)
(* src = "D:/pipe_MIPS32.v:1.1-129.10" *)
module pipe_MIPS32(clk1, clk2);
  (* src = "D:/pipe_MIPS32.v:1.26-1.30" *)
  input clk1;
  wire clk1;
  (* src = "D:/pipe_MIPS32.v:1.39-1.43" *)
  input clk2;
  wire clk2;
  (* src = "D:/pipe_MIPS32.v:20.9-20.15" *)
  wire HALTED;
  (* src = "D:/pipe_MIPS32.v:21.9-21.21" *)
  wire TAKEN_BRANCH;
  assign HALTED = 1'h1;
  assign TAKEN_BRANCH = 1'h1;
endmodule
